### ISSUE TITLE
Support for GHC 9.0.1

### ISSUE THREAD

**Issue by sjakobi** [DanBurton/lens-family-th#18]
This package fails to build even with `--allow-newer`. This patch should probably fix it: https://gitlab.haskell.org/ghc/head.hackage/-/blob/ea1b6b35e46870fea5a9596fcac8df0b9cd105bd/patches/lens-family-th-0.5.1.0.patch

**Comment by DanBurton** [comment]
Thanks for the tip. I'm not sure what's going on with this part of the patch. I assume it's for some future change. It wasn't necessary for ghc 9.0.1 compat so I didn't include it yet.

```diff
 deconstructReconstruct :: Con -> String -> (Pat, Exp)
 deconstructReconstruct c nameBase = (pat, expr) where
-  pat = ConP conN (map VarP argNames)
+  pat = ConP conN
+-- TODO: Use MIN_VERSION_template_haskell(2,18,0) here (see https://gitlab.haskell.org/ghc/ghc/-/issues/19083)
+#if __GLASGOW_HASKELL__ >= 901
+             []
+#endif
+             (map VarP argNames)
```

**Comment by sjakobi** [comment]
Yeah, that's probably meant for GHC 9.2. Thanks for the quick response and release! :)
